import React,{useEffect,useRef,useState} from 'react';
import {Eye,EyeOff,UserPlus} from 'lucide-react';
import {request} from './request.js';
import './operations.css';
export const roleNames={ANALYST:'Regional Sales Analyst',CCO:'CCO · All-region oversight',RBM:'Regional Business Manager',ZONAL_LEAD:'Zonal Lead',CLUSTER_SUPERVISOR:'Cluster Supervisor'};
const regionNames={ALL:'All regions',LAG:'Lagos',NOR:'North',SSE:'South West / South East'};
export default function AccessManagement(){
 const [accounts,setAccounts]=useState([]),[options,setOptions]=useState([]),[form,setForm]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false);
 const editorRef=useRef(null);
 useEffect(()=>{if(form){editorRef.current?.scrollIntoView?.({behavior:'smooth',block:'start'});editorRef.current?.querySelector('input')?.focus({preventScroll:true});}},[form?.id,!!form]);
 const edit=account=>{setForm({...account,password:''});setShow(false);setError('');setMessage('');};
 const load=()=>Promise.all([request('/api/auth/accounts'),request('/api/auth/accounts/options')]).then(([a,o])=>{setAccounts(a.accounts);setOptions(o.assignments);});
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const fresh=()=>{setForm({name:'',email:'',role:'RBM',region:'LAG',zone:'',clusterName:'',active:false,password:''});setShow(false);setError('');};
 async function preview(body){setBusy(true);setError('');try{await request('/api/auth/preview',{method:'POST',body:JSON.stringify(body)});location.reload();}catch(e){setError(e.message);setBusy(false);}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await request(form.id?`/api/auth/accounts/${form.id}/profile`:'/api/auth/accounts',{method:form.id?'PATCH':'POST',body:JSON.stringify(form)});setForm(null);setMessage('Profile saved. You can preview the view before sharing the login details.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const owner=form?.email==='liltomsky@gmail.com';
 return <main className="regional-content access-page"><div className="ops-heading"><div><h1>Manage access</h1><p>Profile your team, assign their scope and preview their dashboard before sharing credentials.</p></div><button className="button primary" onClick={fresh}><UserPlus size={17}/>Create profile</button></div><p className="body-note">Only your account can manage access. Analysts edit people in their assigned region; leaders have viewing access. Preview mode is read-only.</p>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {form&&<section ref={editorRef} className="panel access-editor" aria-label="Account profile editor"><h2>{form.id?'Edit profile':'New profile'}</h2><form onSubmit={save}><div className="access-grid"><label>Name<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" required disabled={!!form.id} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select aria-label="Profile role" disabled={owner} value={form.role} onChange={e=>setForm({...form,role:e.target.value,region:e.target.value==='CCO'?'ALL':form.region==='ALL'?'LAG':form.region,zone:'',clusterName:''})}>{Object.entries(roleNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>{form.role==='ANALYST'?'People-editing region':'Region'}<select aria-label="Profile region" disabled={owner||form.role==='CCO'} value={form.region} onChange={e=>setForm({...form,region:e.target.value,zone:'',clusterName:''})}>{(owner||form.role==='CCO'?['ALL']:['LAG','NOR','SSE']).map(id=><option value={id} key={id}>{regionNames[id]}</option>)}</select></label>
 {['ZONAL_LEAD','CLUSTER_SUPERVISOR'].includes(form.role)&&<label>Zone / state<select required aria-label="Profile zone" value={form.zone} onChange={e=>setForm({...form,zone:e.target.value,clusterName:''})}><option value="">Choose zone / state</option>{[...new Set(options.filter(o=>o.region===form.region).map(o=>o.zone))].map(z=><option key={z}>{z}</option>)}</select></label>}
 {form.role==='CLUSTER_SUPERVISOR'&&<label>Cluster<select required aria-label="Profile cluster" value={form.clusterName} onChange={e=>setForm({...form,clusterName:e.target.value})}><option value="">Choose cluster</option>{options.filter(o=>o.region===form.region&&o.zone===form.zone).map(o=><option key={o.clusterName}>{o.clusterName}</option>)}</select></label>}
 <label>{form.id?'New password (leave blank to keep)':'Password to share'}<div className="access-password"><input aria-label="Profile password" type={show?'text':'password'} required={!form.id} minLength={4} maxLength={72} pattern=".*[A-Z].*" title="At least 4 characters including one capital letter" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" className="icon-button" aria-label={show?'Hide profile password':'Show profile password'} onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div><small>Minimum 4 characters, including one capital letter. Passwords are not retrievable after saving. Copy your chosen password before saving, or set a new one later.</small></label><label>Login access<select aria-label="Profile login access" disabled={owner} value={form.active?'enabled':'disabled'} onChange={e=>setForm({...form,active:e.target.value==='enabled'})}><option value="disabled">Disabled — prepare and preview</option><option value="enabled">Enabled — ready to sign in</option></select></label></div>
 <div className="ops-actions"><button className="button primary" disabled={busy}>Save profile</button><button type="button" className="button" disabled={busy} onClick={()=>preview({role:form.role,region:form.region,zone:form.zone,clusterName:form.clusterName})}><Eye size={16}/>Preview this assignment</button><button type="button" className="button" disabled={busy} onClick={()=>setForm(null)}>Cancel</button></div><p className="body-note">Previewing an unsaved assignment opens its restricted view; save your profile first if you want to keep the form details.</p></form></section>}
 <div className="panel table-scroll"><table><thead><tr><th>Name / email</th><th>Role</th><th>Viewing scope</th><th>People editing</th><th>Login</th><th>Actions</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><button type="button" className="text-button" aria-label={`Edit ${a.name}`} onClick={()=>edit(a)}>{a.name}</button><small className="cell-note">{a.email}</small></td><td>{a.permissions.manageAccess?'Owner · Regional Sales Analyst':roleNames[a.role]}{a.titles?.length>0&&<small className="cell-note">{a.titles.join(' · ')}</small>}</td><td>{a.permissions.allRegions?'All regions':a.clusterName||a.zone||regionNames[a.region]}</td><td>{a.permissions.peopleRegions.length?a.permissions.peopleRegions.map(r=>regionNames[r]).join(', '):'View only'}</td><td>{a.active?'Enabled':'Disabled'}</td><td><div className="ops-actions"><button className="text-button" onClick={()=>edit(a)}>Edit profile / password</button>{!a.permissions.manageAccess&&<button className="text-button" onClick={()=>preview({accountId:a.id})}><Eye size={15}/>Preview profile</button>}</div></td></tr>)}</tbody></table></div></main>;
}
