import React,{useEffect,useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Cell,LineChart,Line} from 'recharts';
import {ArrowUpRight,RefreshCw,Download,TrendingUp,Target,ReceiptText,Wallet} from 'lucide-react';
import {performanceTone} from './performance.js';
import {buildManagementOverview} from './management-data.js';
import './management.css';
const ids=['LAG','NOR','SSE'];
const names={LAG:'Lagos',NOR:'North',SSE:'South West / South East'};
const shortNames={LAG:'Lagos',NOR:'North',SSE:'SW / SE'};
const colors={LAG:'#4665e8',NOR:'#0f8f95',SSE:'#9670cc'};
const money=n=>n==null?'—':`₦${Math.round(n).toLocaleString('en-NG')}`;
const compact=n=>n==null?'—':`₦${Math.abs(n)>=1e6?(n/1e6).toFixed(2)+'m':Math.abs(n)>=1000?(n/1000).toFixed(0)+'k':Math.round(n)}`;
const pct=n=>n==null?'—':`${(n*100).toFixed(1)}%`;
function Tip({active,payload,label}){if(!active||!payload?.length)return null;return <div className="management-tip"><strong>{label}</strong>{payload.filter(p=>p.value!=null).map(p=><div key={p.dataKey}><i style={{background:p.color}}/><span>{p.name}</span><b>{money(p.value)}</b></div>)}</div>;}
function Stat({label,value,detail,icon:Icon,tone}){return <section className="management-stat"><div><span>{label}</span><Icon size={20}/></div><strong style={{color:tone?.color}}>{value}</strong><small>{detail}</small></section>;}
export default function ManagementOverview({regions,onOpenRegion,request}){
 const coverage=regions.map(r=>r.reportingAsOf).filter(Boolean).sort()[0]||'2026-09-01';
 const [filters,setFilters]=useState({mode:'mtd',from:'2026-09-01',asOf:coverage}),[draft,setDraft]=useState({mode:'mtd',from:'2026-09-01',asOf:coverage});
 useEffect(()=>{setFilters(f=>({...f,asOf:coverage}));setDraft(f=>({...f,asOf:coverage}));},[coverage]);
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[trend,setTrend]=useState('daily');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.all(ids.map(async regionId=>({regionId,data:await request(`/api/dashboard?region=${regionId}&from=${filters.from}&asOf=${filters.asOf}`,{signal:controller.signal})}))).then(reports=>{setData(buildManagementOverview(reports));setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});return()=>controller.abort();},[filters,revision,request]);
 function exportSummary(){const headers=['Region','From','Through','Monthly target','Sales value','Volume','Monthly achievement %','Expected target','Expected target achieved %','Gap to expected','Forecast'];const rows=data.regions.map(r=>[names[r.regionId],filters.from,filters.asOf,r.target,r.value,r.count,r.achievement==null?null:r.achievement*100,r.expected,r.pace==null?null:r.pace*100,r.gap,r.forecast]);const csv='\uFEFF'+[headers,...rows].map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`management-${filters.from}-to-${filters.asOf}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const s=data?.summary;
 const comparison=data?.regions.map(r=>({name:shortNames[r.regionId],value:r.value,expected:r.expected,pace:r.pace}))||[];
 return <main className="management-overview">
  <div className="management-title"><div><h1>All regions</h1><p>Management overview · September 2026</p></div><div className="management-actions"><button className="button" disabled={loading||!!error||!data} onClick={exportSummary}><Download size={17}/> Export summary</button><button className="button" aria-label="Refresh management overview" disabled={loading} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={17}/></button></div></div>
  <form className="management-filters" onSubmit={e=>{e.preventDefault();setFilters({...draft,from:draft.mode==='mtd'?'2026-09-01':draft.from});}}><label>Period<select aria-label="Management period" value={draft.mode} onChange={e=>setDraft({...draft,mode:e.target.value})}><option value="mtd">Month to date</option><option value="custom">Custom dates</option></select></label>{draft.mode==='custom'&&<label>From<input type="date" aria-label="Management start date" required min="2026-09-01" max={draft.asOf} value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label>}<label>Through<input type="date" aria-label="Management end date" required min={draft.mode==='mtd'?'2026-09-01':draft.from} max={coverage} value={draft.asOf} onChange={e=>setDraft({...draft,asOf:e.target.value})}/></label><button className="button primary" disabled={loading}>Apply dates</button><span>Source coverage through {Number(coverage.slice(-2))} Sep 2026</span></form>
  {loading?<div className="management-state" role="status">Loading all three regions…</div>:error?<div className="management-state" role="alert">Unable to load the complete overview: {error}<button className="button" onClick={()=>setRevision(v=>v+1)}>Retry</button></div>:data&&<>
  <div className="management-kpis">
   <Stat label={filters.mode==='mtd'?'MTD sales value':'Selected sales value'} value={compact(s.value)} detail={`${money(s.value)} across 3 regions`} icon={Wallet}/>
   <Stat label="Sales volume" value={s.count.toLocaleString()} detail="Accepted transactions in selected dates" icon={ReceiptText}/>
   <Stat label="Expected target achieved" value={pct(s.pace)} detail={`${money(s.expected)} expected · gap ${money(s.gap)}`} icon={Target} tone={performanceTone(s.pace)}/>
   <Stat label={filters.from==='2026-09-01'?'Month-end forecast':'Projected month at selected pace'} value={compact(s.forecast)} detail={s.forecast==null?'Select at least one selling day':`${pct(s.target?s.forecast/s.target:null)} of ${compact(s.target)} monthly target · provisional`} icon={TrendingUp}/>
  </div>
  <div className="management-charts">
   <section className="management-panel"><header><h2>Regional sales vs expected</h2><p>Targets prorated to the selected selling days</p></header><div className="management-chart-legend"><span><i style={{background:'#64748b'}}/>Actual sales · graded by achievement</span><span><i style={{background:'#dfe5ef'}}/>Expected target</span></div><div className="management-chart" role="img" aria-label="Regional sales compared with expected target"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={comparison} margin={{left:0,right:18,top:12,bottom:0}} barGap={5}><CartesianGrid horizontal={false} stroke="#edf0f6"/><XAxis type="number" tickFormatter={compact} axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#67768f'}}/><YAxis type="category" dataKey="name" width={72} axisLine={false} tickLine={false} tick={{fontSize:14,fill:'#465672'}}/><Tooltip content={<Tip/>} cursor={{fill:'#f7f9fc'}}/><Bar dataKey="expected" name="Expected target" fill="#dfe5ef" barSize={23} radius={[0,5,5,0]}/><Bar dataKey="value" name="Actual sales" barSize={23} radius={[0,5,5,0]}>{comparison.map(r=><Cell key={r.name} fill={performanceTone(r.pace).color}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="management-tone-guide">{[[.3,'<50%'],[.6,'50–69%'],[.85,'70–99%'],[1,'100%+']].map(([ratio,label])=><span key={label}><i style={{background:performanceTone(ratio).color}}/>{label}</span>)}<small>of expected target</small></div></section>
   <section className="management-panel"><header className="management-trend-heading"><div><h2>Sales over time</h2><p>{trend==='daily'?'Sales recorded each day':'Running total within selected dates'}</p></div><div className="management-toggle">{['daily','cumulative'].map(t=><button key={t} aria-pressed={trend===t} onClick={()=>setTrend(t)}>{t==='daily'?'Daily':'Cumulative'}</button>)}</div></header><div className="management-chart-legend">{ids.map(id=><span key={id}><i style={{background:colors[id]}}/>{shortNames[id]}</span>)}</div><div className="management-chart" role="img" aria-label={`${trend} sales trend by region; lines bridge missing observations`}><ResponsiveContainer width="100%" height="100%"><LineChart data={data.timeline} margin={{left:0,right:18,top:12,bottom:0}}><CartesianGrid vertical={false} stroke="#edf0f6"/><XAxis dataKey="label" tick={{fontSize:12,fill:'#67768f'}} axisLine={false} tickLine={false} minTickGap={16}/><YAxis tickFormatter={compact} tick={{fontSize:12,fill:'#67768f'}} axisLine={false} tickLine={false} width={72}/><Tooltip content={<Tip/>}/>{ids.map(id=><Line key={id} type="linear" dataKey={id+(trend==='cumulative'?'Cumulative':'')} name={names[id]} stroke={colors[id]} strokeWidth={3} dot={{r:3.5,strokeWidth:2,fill:colors[id]}} activeDot={{r:6}} connectNulls={true}/>)}</LineChart></ResponsiveContainer></div><p className="management-chart-note">Lines connect available observations across missing dates; no sales values are filled in. 6 Sep: no source sheet. 9 Sep: Lagos partial; North and South no rows.</p></section>
  </div>
  <div className="management-section-heading"><h2>Regional performance & top agents</h2><span>Top 3 by recorded sales value in selected dates</span></div>
  <div className="management-regions">{data.regions.map(r=>{const meta=regions.find(m=>m.regionId===r.regionId);const tone=performanceTone(r.pace);return <section className="management-region" key={r.regionId} style={{'--region-color':colors[r.regionId]}}><header><div><h2>{names[r.regionId]}</h2><p>RBM · {meta?.rbm||'Not supplied'}</p></div><button className="management-open" onClick={()=>onOpenRegion(r.regionId)} aria-label={`Open ${names[r.regionId]} dashboard`}><ArrowUpRight size={23}/></button></header><div className="management-region-value"><strong>{compact(r.value)}</strong><span>{r.count} sales · {pct(s.value?r.value/s.value:null)} of total</span></div><div className="management-pace-label"><span>Expected target achieved</span><b style={{color:tone.color}}>{pct(r.pace)}</b></div><div className="management-progress" role="img" aria-label={`${names[r.regionId]} expected target achieved ${pct(r.pace)}`}><span style={{width:`${Math.min(100,Math.max(0,(r.pace||0)*100))}%`,background:tone.color}}/></div><dl className="management-region-metrics"><div><dt>Monthly target</dt><dd>{compact(r.target)}</dd></div><div><dt>{filters.from==='2026-09-01'?'Month target achieved':'Selected / month target'}</dt><dd>{pct(r.achievement)}</dd></div><div><dt>Expected target</dt><dd>{compact(r.expected)}</dd></div><div><dt>Gap to expected</dt><dd style={{color:tone.color}}>{compact(r.gap)}</dd></div><div><dt>{filters.from==='2026-09-01'?'Expected month pace':'Selected month pace'}</dt><dd>{pct(r.target?r.expected/r.target:null)}</dd></div><div><dt>Forecast · provisional</dt><dd>{compact(r.forecast)}</dd></div></dl><div className="management-leaderboard"><h3>Top 3 agents</h3>{r.topAgents.length?<ol>{r.topAgents.map((a,i)=><li key={a.id}><span className="management-rank">{i+1}</span><div><strong>{a.name}</strong><small>{a.count} sales · {a.daysSold} days sold</small></div><b>{compact(a.value)}</b></li>)}</ol>:<p>No named agents recorded sales in this period.</p>}<small className="management-agent-note">{r.regionId==='LAG'?'Includes recorded sales outside the active roster.':'Source names; identity mapping awaits the full roster.'}</small></div><footer>{meta?.stores??'—'} store records · {meta?.active??'—'} active executive records</footer></section>;})}</div>
  <details className="management-methods"><summary>Sources and calculation notes</summary><p>Actuals come from the accepted workbooks stored in MongoDB, with the same filters and attribution as each regional dashboard. Monthly targets total {money(s.target)}; expected target uses each region’s selling calendar. Achievement is sales ÷ expected target; gap is sales − expected target. The combined percentage uses combined sales and expected targets.</p><p>Forecast = selected sales ÷ selected selling days × monthly selling days. Custom ranges project a full month at the selected pace. Forecasts are provisional and are unavailable when the selection contains no selling days. Agent rankings use sales value, then transaction count and name to resolve ties; they are not rankings by individual target achievement. Missing targets remain unassigned.</p>{data.regions.map(r=><p key={r.regionId}><strong>{names[r.regionId]}:</strong> {r.data.period.sourceLabel}</p>)}</details>
  </>}
 </main>;
}
