import React,{useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,ChevronRight,MapPin,AlertTriangle} from 'lucide-react';
import {request} from './request.js';
import './operations.css';
const money=n=>n==null?'—':`₦${Math.round(n).toLocaleString('en-NG')}`;
const percent=n=>n==null?'—':`${(n*100).toFixed(1)}%`;
const activity=p=>p.inactive?`Inactive · ${p.consecutiveNoSaleDays} selling days without sales`:p.activity==='COVERAGE_PENDING'?'Upload coverage pending':p.activity==='DEPARTED'?'Departed':p.soldOnAsOf?'Sold on reporting date':`${p.consecutiveNoSaleDays} selling days without sales`;
function Stats({row}){return <div className="ops-stats">{[['Monthly target',money(row.target)],['MTD expected',money(row.expected)],['Sales value / MTD achieved',money(row.value)],['Transaction volume',row.count],['Monthly achievement',percent(row.achievement)],['Expected pace achieved',percent(row.pace)],['Gap to expected',money(row.gap)],['Month-end forecast',money(row.forecast)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;}
export default function Operations({region,account,onAnalytics}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[date,setDate]=useState(''),[zone,setZone]=useState(''),[cluster,setCluster]=useState(''),[person,setPerson]=useState(null),[store,setStore]=useState(null),[search,setSearch]=useState(''),[ranking,setRanking]=useState('HIGH'),[storeSearch,setStoreSearch]=useState(''),[storeMode,setStoreMode]=useState('HIGH');
 useEffect(()=>{const c=new AbortController();setData(null);request(`/api/workspace/operations?region=${region}${date?`&asOf=${date}`:''}`,{signal:c.signal}).then(d=>{setData(d);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[region,date]);
 const selectZone=z=>{setZone(z);setCluster('');setPerson(null);setStore(null);setSearch('');};
 const selectCluster=c=>{setCluster(c.name);setZone(c.zone);setPerson(null);setStore(null);setSearch('');};
 if(error)return <main className="regional-content"><p role="alert" className="form-error">{error}</p></main>;
 if(!data)return <main className="regional-content" role="status">Loading your operational overview…</main>;
 const restrictedCluster=account.role==='CLUSTER_SUPERVISOR',restrictedZone=account.role==='ZONAL_LEAD';
 const chosenCluster=cluster||(restrictedCluster?account.clusterName:''),chosenZone=zone||((restrictedZone||restrictedCluster)?account.zone:'');
 const currentPerson=person?data.people.find(p=>p.executiveId===person):null;
 const selectedCluster=data.clusters.find(c=>c.name===chosenCluster),selectedZone=data.zones.find(z=>z.name===chosenZone);
 const relevant=data.people.filter(p=>(!chosenZone||p.zone===chosenZone)&&(!chosenCluster||p.clusterName===chosenCluster));
 const sorted=list=>[...list].sort((a,b)=>ranking==='LOW'?a.value-b.value:b.value-a.value);
 const people=sorted(relevant.filter(p=>(ranking!=='INACTIVE'||p.inactive)&&(ranking!=='NO_SALE'||!p.soldOnAsOf)&&(ranking!=='ZERO'||p.count===0)&&[p.name,p.clusterName,p.state,p.storeName].join(' ').toLowerCase().includes(search.toLowerCase())));
 const clusterRows=sorted(data.clusters.filter(c=>!chosenZone||c.zone===chosenZone));
 const summary=currentPerson||selectedCluster||selectedZone||data.summary;
 const transactions=currentPerson?currentPerson.transactions.map(t=>({...t,agent:currentPerson.name,clusterName:currentPerson.clusterName})):data.transactions.filter(t=>(!chosenZone||t.zone===chosenZone)&&(!chosenCluster||t.clusterName===chosenCluster));
 const storeRows=data.stores.filter(s=>(!chosenCluster||s.clusterName===chosenCluster)&&(!chosenZone||chosenCluster||data.clusters.some(c=>c.zone===chosenZone&&c.name===s.clusterName))&&(!currentPerson||currentPerson.assignedStores.some(x=>x.id===s.id)));
 const displayedStores=storeRows.filter(s=>(storeMode!=='ZERO'||s.count===0)&&[s.name,s.address,s.state].join(' ').toLowerCase().includes(storeSearch.toLowerCase())).sort((a,b)=>storeMode==='LOW'?a.value-b.value:b.value-a.value);
 const root=()=>{setZone('');setCluster('');setPerson(null);setStore(null);};
 return <main className="regional-content operations-page"><div className="ops-heading"><div><h1>{data.scope} overview</h1><p>{data.regionalLead||'Regional operations'} · Month to date through {data.asOf}</p></div><div className="ops-actions"><label>Through<input aria-label="Operations through" type="date" min="2026-09-01" max={data.maxDate} value={data.asOf} onChange={e=>{setDate(e.target.value);setPerson(null);setStore(null);}}/></label><button className="button" onClick={onAnalytics}>Sales analytics<ArrowRight size={16}/></button></div></div>
 <nav className="ops-trail" aria-label="Performance hierarchy"><button onClick={root}>{data.scope}</button>{chosenZone&&!restrictedZone&&!restrictedCluster&&<><ChevronRight size={14}/><button onClick={()=>selectZone(chosenZone)}>{chosenZone} · {selectedZone?.leader||'No zonal lead'}</button></>}{chosenCluster&&<><ChevronRight size={14}/><button onClick={()=>{setPerson(null);setStore(null);}}>{chosenCluster} · {selectedCluster?.supervisor}</button></>}{currentPerson&&<><ChevronRight size={14}/><button onClick={()=>setStore(null)}>{currentPerson.name}</button></>}{store&&<><ChevronRight size={14}/><span>{store}</span></>}</nav>
 <Stats row={summary}/>
 {!chosenZone&&!chosenCluster&&!currentPerson&&<div className="ops-coverage">{[['Total MBEs',data.summary.totalMbes],['Active employment',data.summary.activeMbes],['Inactive sales flag',data.summary.inactiveMbes],['Zero-sale MBEs',data.summary.zeroSaleMbes],['Registered stores',data.summary.totalStores],['Active store status',data.summary.activeStores],['Productive matched stores',data.summary.productiveStores],['No matched sale',data.summary.zeroSaleStores]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div>}
 {currentPerson&&<section className={`ops-alert ${currentPerson.inactive?'warning':''}`}><AlertTriangle size={19}/><div><strong>{activity(currentPerson)}</strong><p>Last recorded sale: {currentPerson.lastSale||'No recorded sale'} · Previous sales remain in performance totals.</p><p>{currentPerson.state||currentPerson.zone} · {currentPerson.clusterName} · Employment: {currentPerson.status.toLowerCase()}</p></div></section>}
 {!chosenCluster&&!currentPerson&&<><div className="ops-section-title"><h2>{chosenZone?'Cluster comparison':'Zones / states and leadership'}</h2><label>Rank by<select aria-label="Performance ranking" value={ranking} onChange={e=>setRanking(e.target.value)}><option value="HIGH">Highest sales</option><option value="LOW">Lowest sales / intervention</option></select></label></div>{!chosenZone&&<div className="ops-zones">{sorted(data.zones).map(z=><button key={z.name} className="ops-zone" onClick={()=>selectZone(z.name)}><span>{z.name}</span><strong>{z.leader||'State → clusters and supervisors'}</strong><b>{money(z.value)}</b><small>{z.count} transactions · {percent(z.pace)} of expected</small><div className="ops-bar"><i style={{width:`${Math.min((z.pace||0)*100,100)}%`}}/></div><small>Target {money(z.target)} · Forecast {money(z.forecast)}</small><span className="ops-link">View clusters <ArrowRight size={15}/></span></button>)}</div>}<div className="panel table-scroll"><table><thead><tr><th>Cluster / supervisor</th><th>Monthly allocated target</th><th>Expected MTD</th><th>Sales value</th><th>Count</th><th>Monthly achieved</th><th>Gap to expected</th><th>Forecast</th><th>MBEs / inactive</th></tr></thead><tbody>{clusterRows.map(c=><tr key={c.name}><td><button className="agent-link" onClick={()=>selectCluster(c)}>{c.name}<ArrowUpRight size={14}/></button><small className="cell-note">{c.supervisor}</small></td><td>{money(c.target)}</td><td>{money(c.expected)}</td><td>{money(c.value)}</td><td>{c.count}</td><td>{percent(c.achievement)}</td><td>{money(c.gap)}</td><td>{money(c.forecast)}</td><td>{c.mbeCount} / {c.inactiveCount}</td></tr>)}</tbody></table></div></>}
 {!currentPerson&&<section><div className="ops-section-title"><h2>{chosenCluster?`${chosenCluster} · ${selectedCluster?.supervisor||'Supervisor pending'}`:'MBE performance and intervention'}</h2><div className="ops-actions"><input aria-label="Search operational MBEs" placeholder="Search MBE or location" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="MBE performance filter" value={ranking} onChange={e=>setRanking(e.target.value)}><option value="HIGH">Top-performing MBEs</option><option value="LOW">Low-performing MBEs</option><option value="INACTIVE">Inactive: 3 selling days</option><option value="NO_SALE">No sale on reporting date</option><option value="ZERO">Zero sales MTD</option></select></div></div><div className="panel table-scroll"><table><thead><tr><th>MBE / cluster</th><th>Target / expected</th><th>MTD sales / volume</th><th>Achievement</th><th>Gap / forecast</th><th>Last sale</th><th>Sales activity</th><th>Stores</th></tr></thead><tbody>{people.map(p=><tr key={p.executiveId}><td><button className="agent-link" onClick={()=>{setPerson(p.executiveId);setStore(null);}}>{p.name}<ArrowUpRight size={14}/></button><small className="cell-note">{p.clusterName}</small></td><td>{money(p.target)}<small className="cell-note">Expected {money(p.expected)}</small></td><td>{money(p.value)}<small className="cell-note">{p.count} sales</small></td><td>{percent(p.achievement)}</td><td>{money(p.gap)}<small className="cell-note">Forecast {money(p.forecast)}</small></td><td>{p.lastSale||'Never recorded'}</td><td><span className={p.inactive?'ops-inactive':''}>{activity(p)}</span></td><td>{p.assignedStores.length} confirmed<small className="cell-note">{p.reportedStores.length} reported</small></td></tr>)}</tbody></table>{!people.length&&<p className="body-note">No MBEs match this view.</p>}</div></section>}
 <section><div className="ops-section-title"><h2>{currentPerson?'Assigned stores and locations':'Store performance and locations'}</h2><div className="ops-actions"><input aria-label="Search operational stores" placeholder="Store or location" value={storeSearch} onChange={e=>setStoreSearch(e.target.value)}/><select aria-label="Store performance filter" value={storeMode} onChange={e=>setStoreMode(e.target.value)}><option value="HIGH">Top-performing stores</option><option value="LOW">Low-performing stores</option><option value="ZERO">No matched sales</option></select></div></div><p className="body-note">{storeRows.length} registered stores in this view. Sales are linked only when the store matches uniquely; “no matched sale” may also mean a missing link.</p><div className="panel table-scroll"><table><thead><tr><th>Store</th><th>Location</th><th>Status</th><th>Sales value</th><th>Count</th><th>Last sale in period</th></tr></thead><tbody>{displayedStores.slice(0,30).map(s=><tr key={s.id}><td><button className="agent-link" onClick={()=>setStore(s.name)}>{s.name}<ArrowUpRight size={14}/></button><small className="cell-note">{s.id}</small></td><td>{s.address}<small className="cell-note">{s.state} · {s.clusterName}</small></td><td>{s.status==='UNKNOWN'?'Status unconfirmed':s.status.toLowerCase()}</td><td>{money(s.value)}</td><td>{s.count}</td><td>{s.lastSale||'No matched sale'}</td></tr>)}</tbody></table>{!displayedStores.length&&<p className="body-note">No confirmed store assignments match this view.</p>}</div>{displayedStores.length>30&&<p className="body-note">Showing the first 30 of {displayedStores.length}. Search to find a specific store.</p>}
 {currentPerson&&<><h3>Locations reported on sales</h3><p className="body-note">These source labels show where sales were recorded; they do not establish a confirmed store assignment.</p><div className="ops-actions">{currentPerson.reportedStores.map(s=><button className="button" key={s} onClick={()=>setStore(s)}><MapPin size={14}/>{s}</button>)}</div></>}
 </section>
 {(currentPerson||store)&&<section><div className="ops-section-title"><h2>{store||currentPerson.name} · individual transactions</h2>{store&&<button className="text-button" onClick={()=>setStore(null)}>Show all MBE transactions</button>}</div><div className="panel table-scroll"><table><thead><tr><th>Date</th><th>MBE</th><th>Store</th><th>Policy ID</th><th>Plan / device</th><th>Value</th></tr></thead><tbody>{transactions.filter(t=>!store||t.store===store).map(t=><tr key={t.id}><td>{t.date}</td><td>{t.agent}</td><td>{t.store}</td><td>{t.id}</td><td>{t.plan}<small className="cell-note">{t.device}</small></td><td>{money(t.value)}</td></tr>)}</tbody></table>{!transactions.filter(t=>!store||t.store===store).length&&<p className="body-note">No matched transactions in this view.</p>}</div></section>}
 {data.unassigned.count>0&&!currentPerson&&<p className="body-note">{data.unassigned.count} sales / {money(data.unassigned.value)} have no unique registered MBE match. They remain included in this scope’s totals.</p>}
 <div className="ops-notes">{data.notes.map(n=><p key={n}>{n}</p>)}</div>
 </main>;
}
