import React, {useEffect,useMemo,useRef,useState} from 'react';
import {Users,UserPlus,Search,X,ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';
import {request} from './request.js';
import './people.css';

const names={LAG:'Lagos',NOR:'North',SSE:'SW / SE'};
const money=value=>`₦${Math.round(value).toLocaleString('en-NG')}`;
const departed=person=>['RESIGNED','EXITED'].includes(person.status);
const today=()=>new Date().toLocaleDateString('en-CA');
function Dialog({title,onClose,children,wide=false}){
  const ref=useRef(null);
  useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current.querySelector('button').focus();return()=>{document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus();};},[]);
  return <div className="people-backdrop" onClick={onClose}><section ref={ref} className={`people-dialog ${wide?'people-dialog-wide':''}`} role="dialog" aria-modal="true" aria-labelledby="people-dialog-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input,select,textarea')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><header><h2 id="people-dialog-title">{title}</h2><button className="icon-button" aria-label="Close people dialog" onClick={onClose}><X size={22}/></button></header>{children}</section></div>;
}
function Field({label,...props}){return <label>{label}<input {...props}/></label>;}

export default function PeopleManagement({region,regions,account}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
  const [search,setSearch]=useState(''),[status,setStatus]=useState('CURRENT'),[page,setPage]=useState(0),[filters,setFilters]=useState({from:'2026-09-01',asOf:''}),[draft,setDraft]=useState({from:'2026-09-01',asOf:''});
  const [selected,setSelected]=useState(null),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[message,setMessage]=useState('');
  const editable=account?.permissions?.peopleRegions||[];
  const canEdit=r=>editable.includes(r);
  const [newRegion,setNewRegion]=useState(region==='ALL'?'LAG':region);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData(null);const params=new URLSearchParams({region,from:filters.from,...(filters.asOf?{asOf:filters.asOf}:{})});request(`/api/workspace/people?${params}`,{signal:controller.signal}).then(d=>{setData(d);setDraft({from:d.from,asOf:d.asOf});setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});return()=>controller.abort();},[region,filters,revision]);
  useEffect(()=>setPage(0),[search,status,filters,revision]);
  const rows=useMemo(()=>(data?.people||[]).filter(p=>status==='ALL'||status==='CURRENT'&&!departed(p)||status==='DEPARTED'&&departed(p)||p.status===status).filter(p=>[p.name,p.executiveId,p.state,p.clusterName,p.storeName,names[p.region]].join(' ').toLowerCase().includes(search.toLowerCase())),[data,search,status]);
  const pages=Math.max(1,Math.ceil(rows.length/20)),currentPage=Math.min(page,pages-1);
  function openForm(value){setFormError('');setNewRegion(region==='ALL'?(editable[0]||'LAG'):region);setForm(value);}
  async function save(event){event.preventDefault();setBusy(true);setFormError('');const body=Object.fromEntries(new FormData(event.currentTarget));try{const adding=form.type==='add';await request(adding?'/api/workspace/executives':`/api/workspace/executives/${encodeURIComponent(form.person.executiveId)}`,{method:adding?'POST':'PATCH',body:JSON.stringify({...body,region:adding?newRegion:form.person.region})});setMessage(adding?'Sales executive added.':'Status updated. Historical sales are preserved.');setForm(null);setSelected(null);setRevision(v=>v+1);}catch(e){setFormError(e.message);}finally{setBusy(false);}}
  return <main className="people-page">
    <div className="people-heading"><div><div className="eyebrow">PEOPLE MANAGEMENT</div><h1>Sales executives</h1><p>{region==='ALL'?'All regions':names[region]} · Manage your team and explore individual sales performance.</p></div>{(region==='ALL'?editable.length>0:canEdit(region))&&<button className="button primary" onClick={()=>openForm({type:'add'})}><UserPlus size={17}/> Add sales executive</button>}</div>
    {message&&<p role="status" className="people-message">{message}</p>}
    <div className="people-stats">{[['Total registered',data?.people.length],['Active',data?.people.filter(p=>p.status==='ACTIVE').length],['Status pending',data?.people.filter(p=>p.status==='UNKNOWN').length],['Resigned / exited',data?.people.filter(departed).length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div>
    <div className="people-toolbar"><label className="people-search"><Search size={17}/><input aria-label="Search sales executives" placeholder="Search name, ID, cluster or state" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>People shown<select aria-label="Executive status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="CURRENT">Current team</option><option value="ACTIVE">Active</option><option value="UNKNOWN">Status pending</option><option value="INACTIVE">Inactive</option><option value="DEPARTED">Resigned / exited</option><option value="ALL">Everyone</option></select></label>
      <form className="people-date-form" onSubmit={e=>{e.preventDefault();setSelected(null);setFilters({...draft});}}><Field label="Sales from" aria-label="People sales from" type="date" required min="2026-09-01" max={draft.asOf||undefined} value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/><Field label="Through" aria-label="People sales through" type="date" required min={draft.from} max={data?.maxDate} value={draft.asOf} onChange={e=>setDraft({...draft,asOf:e.target.value})}/><button className="button" disabled={loading}>Apply</button></form>
    </div>
    {error?<div className="people-empty" role="alert">{error}<button className="button" onClick={()=>setRevision(v=>v+1)}>Retry</button></div>:loading?<div className="people-empty" role="status">Loading sales executives…</div>:<>
      <div className="people-table-heading"><span>{rows.length} executives · sales from {data.from} to {data.asOf}</span><small>Click a name to view performance</small></div>
      <div className="panel table-scroll"><table className="people-table"><thead><tr><th>Sales executive</th><th>Region / location</th><th>Status</th><th>Sales count</th><th>Sales value</th><th>Days sold</th><th>Actions</th></tr></thead><tbody>{rows.slice(currentPage*20,currentPage*20+20).map(p=><tr key={p.executiveId}><td><button className="people-name" onClick={()=>setSelected(p)}>{p.name}<ArrowUpRight size={14}/></button><small>{p.executiveId}</small>{p.matchStatus.includes('unverified')||p.matchStatus.includes('Ambiguous')?<small className="people-match">{p.matchStatus}</small>:null}</td><td>{names[p.region]}<small>{[p.state,p.clusterName].filter(Boolean).join(' · ')||'Location pending'}</small></td><td><span className={`people-status status-${p.status.toLowerCase()}`}>{p.status==='UNKNOWN'?'Status pending':p.status.toLowerCase()}</span></td><td>{p.count}</td><td className="people-value">{money(p.value)}</td><td>{p.daysSold}<small>Last sale: {p.lastSale||'Never recorded'}</small>{p.inactive&&<small className="ops-inactive">Inactive · {p.consecutiveNoSaleDays} selling days</small>}</td><td><div className="people-actions"><button className="text-button" onClick={()=>setSelected(p)}>Performance</button>{canEdit(p.region)&&<button className="text-button" onClick={()=>openForm({type:'status',person:p,status:departed(p)?'ACTIVE':'RESIGNED'})}>{departed(p)?'Update status':'Record resignation'}</button>}</div></td></tr>)}</tbody></table>{!rows.length&&<div className="people-empty"><Users size={24}/><p>No executives match this view.</p></div>}</div>
      <div className="people-pagination"><span>Page {currentPage+1} of {pages}</span><button aria-label="Previous executives page" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={18}/></button><button aria-label="Next executives page" disabled={currentPage===pages-1} onClick={()=>setPage(currentPage+1)}><ChevronRight size={18}/></button></div>
      {!!data.unassigned.count&&<p className="people-footnote">{data.unassigned.count} sales / {money(data.unassigned.value)} in this period cannot be assigned uniquely to a registered executive. They remain in dashboard totals.</p>}
    </>}
    {selected&&!form&&<Performance person={selected} from={data.from} asOf={data.asOf} onClose={()=>setSelected(null)} onStatus={canEdit(selected.region)?()=>openForm({type:'status',person:selected,status:selected.status==='UNKNOWN'?'ACTIVE':selected.status}):null}/>}
    {form&&<Dialog title={form.type==='add'?'Add sales executive':`Update ${form.person.name}`} onClose={()=>{if(!busy)setForm(null);}}><form className="people-form" onSubmit={save}>
      {form.type==='add'?<><Field label="Full name" name="name" required minLength={2} maxLength={150}/><label>Region<select aria-label="New executive region" value={newRegion} onChange={e=>setNewRegion(e.target.value)} disabled={region!=='ALL'}>{regions.filter(r=>canEdit(r.regionId)&&(region==='ALL'||r.regionId===region)).map(r=><option key={r.regionId} value={r.regionId}>{r.name}</option>)}</select></label><Field label="State" name="state"/><Field label="Joining date" name="joinedOn" type="date" required max={today()}/>{newRegion==='LAG'?<label>Cluster<select name="clusterId"><option value="">Not assigned yet</option>{data?.clusters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<Field label="Cluster" name="clusterName"/>}<Field label="Store / location" name="storeName"/></>:<><p>Resigned or exited MBEs leave the current-team list. Their sales and status history remain available.</p><label>Status<select name="status" defaultValue={form.status}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="RESIGNED">Resigned</option><option value="EXITED">Exited</option></select></label><Field label="Effective date" name="effectiveDate" type="date" required min={form.person.joinedOn||undefined} max={today()}/><label>Reason<textarea name="reason" required rows={3}/></label></>}
      {formError&&<p className="form-error" role="alert">{formError}</p>}<div className="people-form-actions"><button className="button" type="button" disabled={busy} onClick={()=>setForm(null)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':form.type==='add'?'Add executive':'Save status'}</button></div>
    </form></Dialog>}
  </main>;
}

function Performance({person,from,asOf,onClose,onStatus}){
  const [data,setData]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(0);
  useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({region:person.region,executiveId:person.executiveId,from,asOf});request(`/api/workspace/people?${query}`,{signal:controller.signal}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[person.executiveId,person.region,from,asOf]);
  const p=data?.person;
  return <Dialog title={person.name} onClose={onClose} wide>{error?<p role="alert">{error}</p>:!p?<p role="status">Loading performance…</p>:<>
    <p className="people-profile-meta">{names[p.region]} · {p.executiveId} · {p.status.toLowerCase()}<br/>{from} to {asOf}</p><p className="people-footnote">{p.matchStatus}</p>
    <div className="people-stats"><div><span>Sales value</span><strong>{money(p.value)}</strong></div><div><span>Sales count</span><strong>{p.count}</strong></div><div><span>Days sold</span><strong>{p.daysSold}</strong></div><div><span>Average sale</span><strong>{money(p.average)}</strong></div></div>
    <div className="people-profile-details"><span>Joined: {p.joinedOn||'Not recorded'}</span><span>Exited: {p.exitedOn||'—'}</span><span>Last sale in period: {p.lastSale||'—'}</span>{onStatus&&<button className="text-button" onClick={onStatus}>Update employment status</button>}</div>
    <h3>Sales transactions</h3><div className="table-scroll"><table className="people-table"><thead><tr><th>Date</th><th>Store / cluster</th><th>Plan / device</th><th>Value</th></tr></thead><tbody>{p.transactions.slice(page*15,page*15+15).map(t=><tr key={t.id}><td>{t.date}</td><td>{t.store}<small>{t.cluster}</small></td><td>{t.plan}<small>{t.device}</small></td><td>{money(t.value)}</td></tr>)}</tbody></table>{!p.count&&<p>No matched sales in the selected period.</p>}</div>
    {p.count>15&&<div className="people-pagination"><span>Page {page+1} of {Math.ceil(p.count/15)}</span><button aria-label="Previous sales page" disabled={!page} onClick={()=>setPage(page-1)}><ChevronLeft size={18}/></button><button aria-label="Next sales page" disabled={(page+1)*15>=p.count} onClick={()=>setPage(page+1)}><ChevronRight size={18}/></button></div>}
    <h3>Employment history</h3>{data.events.length?data.events.map(e=><div className="people-history" key={e._id}><strong>{e.action} · {e.effectiveDate||'Date not recorded'}</strong><p>{e.reason}</p></div>):<p>No employment changes recorded.</p>}
  </>}</Dialog>;
}
