import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Search,ArrowUpRight,X,Download,ClipboardList} from 'lucide-react';
import {request} from './request.js';
import './reconciliation.css';

const money=value=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(value/100);
const regions={LAG:'Lagos',NOR:'North',SSE:'SW / SE',UNKNOWN:'Region unconfirmed'};
const labels={DATE_CONFLICT:'Date conflict',PAYMENT_STATUS:'Payment status',PAYMENT_MISMATCH:'Payment mismatch',RENEWAL_UNVERIFIED:'Renewal verification',REGION_UNKNOWN:'Unknown region',CLUSTER_UNRESOLVED:'Cluster unassigned',CLUSTER_CONFLICT:'Cluster conflict',AGENT_UNRESOLVED:'Agent unassigned',STORE_MISSING:'Missing store',MISSING_FROM_REPLACEMENT:'Missing from new source',PREVIOUS_HOLD_UNRESOLVED:'Previous unresolved hold',AMOUNT_CONFLICT:'Amount conflict'};
const statusLabel={OPEN:'Open',IN_REVIEW:'In review',RESOLVED:'Reviewed'};
const date=value=>value?new Date(`${value}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'Not supplied';
const csvCell=value=>{let text=String(value??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};

export default function Reconciliation({region}){
  const [cases,setCases]=useState(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('UNRESOLVED'),[treatment,setTreatment]=useState('ALL'),[issue,setIssue]=useState('ALL'),[selected,setSelected]=useState(null),[page,setPage]=useState(0);
  const load=()=>request(`/api/workspace/reconciliation?region=${region}`).then(d=>{setCases(d.cases);setError('');return d.cases;});
  useEffect(()=>{let live=true;request(`/api/workspace/reconciliation?region=${region}`).then(d=>{if(live)setCases(d.cases);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[region]);
  useEffect(()=>setPage(0),[search,status,treatment,issue]);
  const filtered=useMemo(()=>(cases||[]).filter(c=>(status==='ALL'||status==='UNRESOLVED'&&c.status!=='RESOLVED'||c.status===status)&&(treatment==='ALL'||c.treatment===treatment)&&(issue==='ALL'||c.issues.some(i=>i.code===issue))&&[c.policyId,c.agentName,c.storeName,c.clusterName,c.zone,regions[c.region],c.sourceFile,...c.issues.map(i=>i.message)].join(' ').toLowerCase().includes(search.toLowerCase())),[cases,search,status,treatment,issue]);
  const included=filtered.filter(c=>c.treatment==='INCLUDED'),held=filtered.filter(c=>c.treatment==='HELD'),sum=rows=>rows.reduce((n,r)=>n+r.valueKobo,0);
  function download(){
    const headings=['Policy ID','Reporting date','Worksheet date','Recorded timestamp','Region','Agent','Store','Zone / state','Cluster','Value NGN','Payment status','Treatment','Review status','Issues','Next steps','Source file','Sheet','Row','Review notes'];
    const rows=filtered.map(c=>[c.policyId,c.businessDate,c.sheetDate,c.sourceTimestamp,regions[c.region],c.agentName,c.storeName,c.zone,c.clusterName,c.valueKobo/100,c.paymentStatus,c.treatment,statusLabel[c.status],c.issues.map(i=>i.message).join(' | '),c.issues.map(i=>i.nextStep).join(' | '),c.sourceFile,c.sheet,c.rowNumber,c.history.map(h=>`${h.at}: ${h.note}`).join(' | ')]);
    const url=URL.createObjectURL(new Blob(['\uFEFF'+[headings,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`reconciliation-${region.toLowerCase()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  return <main className="regional-content reconciliation-page"><div className="reconciliation-heading"><div><h1>Reconciliation</h1><p>Review unclear sales, their source details and the action needed.</p></div><button className="button" disabled={!filtered.length} onClick={download}><Download size={17}/>Export current view</button></div>
    {error&&<div role="alert" className="form-error">{error} <button className="text-button" onClick={()=>load().catch(e=>setError(e.message))}>Retry</button></div>}
    <div className="reconciliation-summary"><div><span>Transactions in this view</span><strong>{cases?filtered.length:'—'}</strong><small>Each transaction counted once, even with multiple issues</small></div><div><span>Included in sales · {included.length}</span><strong>{cases?money(sum(included)):'—'}</strong><small>Already counted; confirm the flagged details</small></div><div><span>Held outside sales · {held.length}</span><strong>{cases?money(sum(held)):'—'}</strong><small>Excluded until the sales record is corrected or approved</small></div></div>
    <div className="reconciliation-filters"><label className="reconciliation-search"><span>Search transactions</span><div><Search size={17}/><input aria-label="Search reconciliation" placeholder="Agent, store, policy ID or issue" value={search} onChange={e=>setSearch(e.target.value)}/></div></label><label>Review status<select aria-label="Review status" value={status} onChange={e=>setStatus(e.target.value)}><option value="UNRESOLVED">Open and in review</option><option value="ALL">All statuses</option><option value="OPEN">Open</option><option value="IN_REVIEW">In review</option><option value="RESOLVED">Reviewed</option></select></label><label>Sales treatment<select aria-label="Sales treatment" value={treatment} onChange={e=>setTreatment(e.target.value)}><option value="ALL">Included and held</option><option value="INCLUDED">Included in sales</option><option value="HELD">Held outside sales</option></select></label><label>Issue<select aria-label="Issue" value={issue} onChange={e=>setIssue(e.target.value)}><option value="ALL">All issues</option>{[...new Set((cases||[]).flatMap(c=>c.issues.map(i=>i.code)))].sort().map(code=><option key={code} value={code}>{labels[code]||code}</option>)}</select></label></div>
    <div className="panel"><div className="table-scroll"><table className="reconciliation-table"><thead><tr><th>Transaction / agent</th><th>Date / location</th><th>Value</th><th>Issue</th><th>Sales treatment</th><th>Review status</th><th>Details</th></tr></thead><tbody>{filtered.slice(page*20,(page+1)*20).map(c=><tr key={c.id}><td><button className="agent-link" onClick={()=>setSelected(c)}>{c.agentName||'Unattributed'}</button><small>{c.storeName||'Store not supplied'}</small><small className="reconciliation-policy" title={c.policyId}>{c.policyId||'No policy ID'}</small></td><td>{date(c.businessDate)}<small>{regions[c.region]} · {c.clusterName||c.zone||'Location unconfirmed'}</small></td><td className="strong">{money(c.valueKobo)}</td><td>{c.issues.map(i=><span className="reconciliation-issue" key={i.code}>{labels[i.code]||i.code}</span>)}</td><td><span className={`reconciliation-badge ${c.treatment.toLowerCase()}`}>{c.treatment==='INCLUDED'?'Included':'Held outside sales'}</span></td><td>{statusLabel[c.status]}</td><td><button className="text-button" aria-label={`View reconciliation for ${c.agentName||c.storeName||c.policyId}, ${c.policyId||c.sheet+' row '+c.rowNumber}`} onClick={()=>setSelected(c)}>View<ArrowUpRight size={16}/></button></td></tr>)}</tbody></table></div>{!cases&&!error&&<p role="status" className="no-results">Loading reconciliation records…</p>}{cases&&!filtered.length&&<div className="no-results"><ClipboardList size={25}/><p>No reconciliation records match these filters.</p></div>}<div className="pagination"><span>{filtered.length?Math.min(page*20+1,filtered.length):0}–{Math.min((page+1)*20,filtered.length)} of {filtered.length}</span><div><button className="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button" disabled={(page+1)*20>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></div>
    {selected&&<CaseDetail record={selected} onClose={()=>setSelected(null)} onSaved={async()=>{const rows=await load();setSelected(rows.find(r=>r.id===selected.id));}}/>}
  </main>;
}
function CaseDetail({record:c,onClose,onSaved}){
  const ref=useRef(null),[status,setStatus]=useState(c.status),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{setStatus(c.status);},[c]);
  useEffect(()=>{const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current.querySelector('button').focus();return()=>{document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus();};},[]);
  async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{await request(`/api/workspace/reconciliation/${c.id}`,{method:'PATCH',body:JSON.stringify({status,note,version:c.version})});await onSaved();setNote('');setMessage('Review saved. Sales totals have not changed.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="drawer-backdrop" onClick={onClose}><section ref={ref} className="drawer reconciliation-detail" role="dialog" aria-modal="true" aria-labelledby="reconciliation-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className="drawer-top"><span>TRANSACTION REVIEW</span><button className="icon-button" aria-label="Close reconciliation detail" onClick={onClose}><X size={22}/></button></div><h2 id="reconciliation-title">{c.agentName||'Unattributed sale'}</h2><p>{c.storeName||'Store not supplied'}</p><div className="reconciliation-amount"><strong>{money(c.valueKobo)}</strong><span className={`reconciliation-badge ${c.treatment.toLowerCase()}`}>{c.treatment==='INCLUDED'?'Included in sales totals':'Held outside sales totals'}</span></div>
    <h3>What needs reconciling</h3>{c.issues.map(i=><div className="reconciliation-reason" key={i.code}><strong>{labels[i.code]||i.code}</strong><p>{i.message}</p><p><b>Next step:</b> {i.nextStep}</p></div>)}
    <h3>Transaction details</h3><dl className="reconciliation-facts">{[['Policy ID',c.policyId||'Not supplied'],['Reporting date',date(c.businessDate)],['Worksheet date',date(c.sheetDate)],['Recorded timestamp',c.sourceTimestamp||'Not supplied'],['Region',regions[c.region]],['Zone / state',c.zone||'Unconfirmed'],['Cluster',c.clusterName||'Unconfirmed'],['Payment status',c.paymentStatus||'Unconfirmed'],['Source workbook',c.sourceFile],['Source location',`${c.sheet} · row ${c.rowNumber}`]].map(([key,value])=><React.Fragment key={key}><dt>{key}</dt><dd>{value}</dd></React.Fragment>)}</dl>
    {c.previous&&<><h3>Previous dashboard record</h3><dl className="reconciliation-facts">{[['Date',c.previous.businessDate],['Recorded timestamp',c.previous.sourceTimestamp],['Value',c.previous.valueKobo!=null?money(c.previous.valueKobo):null],['Zone',c.previous.zone],['Cluster',c.previous.cluster],['Agent',c.previous.agentName]].filter(([,v])=>v).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl></>}
    <h3>Review notes</h3><p className="body-note">Save findings and review progress here. Marking a record reviewed does not add, remove or correct a sale.</p><form className="reconciliation-review-form" onSubmit={save}><label>Review status<select aria-label="Review status" value={status} onChange={e=>setStatus(e.target.value)}><option value="OPEN">Open</option><option value="IN_REVIEW">In review</option><option value="RESOLVED">Reviewed</option></select></label><label>Review note<textarea required minLength={5} maxLength={2000} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the evidence checked and the correction needed."/></label>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<button className="button primary" disabled={busy}>{busy?'Saving…':'Save review'}</button></form>
    {[...c.history].reverse().map((h,i)=><div className="reconciliation-history" key={i}><strong>{h.actor} · {statusLabel[h.status]}</strong><small>{new Date(h.at).toLocaleString()}</small><p>{h.note}</p></div>)}
  </section></div>;
}
