import sapphireLogo from './assets/sapphire-logo.svg';
import WorkspaceMenu from './WorkspaceMenu.jsx';
import {Menu,Eye,EyeOff} from 'lucide-react';
import React,{lazy,Suspense,useEffect,useState,useId} from 'react';
import {request} from './request.js';
export {request} from './request.js';
const AccessManagement=lazy(()=>import('./AccessManagement.jsx'));
const Operations=lazy(()=>import('./Operations.jsx'));
const ManagementOverview=lazy(()=>import('./ManagementOverview.jsx'));
const PeopleManagement=lazy(()=>import('./PeopleManagement.jsx'));
const Reconciliation=lazy(()=>import('./Reconciliation.jsx'));
const roleNames={ANALYST:'Regional Sales Analyst',CCO:'CCO · All-region oversight',RBM:'Regional Business Manager',ZONAL_LEAD:'Zonal Lead',CLUSTER_SUPERVISOR:'Cluster Supervisor'};
function Deferred({children}){return <Suspense fallback={<div className="workspace-loading">Loading workspace…</div>}>{children}</Suspense>;}
const post=(path,body,method='POST')=>request(path,{method,body:JSON.stringify(body)});
function FormField({label,name,type='text',required=true,defaultValue,reveal=false,newPassword=false}){
 const [visible,setVisible]=useState(false),id=useId();
 const input=<input id={id} name={name} type={type==='password'&&visible?'text':type} required={required} defaultValue={defaultValue} minLength={type==='password'&&newPassword?4:undefined} pattern={newPassword?'.*[A-Z].*':undefined} title={newPassword?'At least 4 characters including one capital letter':undefined}/>;
 if(!reveal||type!=='password')return <label htmlFor={id}>{label}{input}</label>;
 return <div className="auth-password-field"><label htmlFor={id}>{label}</label><div className="auth-password-input">{input}<button type="button" className="password-visibility" aria-label={visible?'Hide password':'Show password'} title={visible?'Hide password':'Show password'} aria-controls={id} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></div>;
}
export default function Workspace({LagosDashboard}){
 const [menuOpen,setMenuOpen]=useState(false);
 const [account,setAccount]=useState(null),[ready,setReady]=useState(false),[setup,setSetup]=useState(false),[regions,setRegions]=useState([]),[region,setRegion]=useState('LAG'),[view,setView]=useState('dashboard'),[error,setError]=useState(''),[recovering,setRecovering]=useState(false);
 useEffect(()=>{const expire=()=>setAccount(null);window.addEventListener('session-expired',expire);request('/api/auth/status').then(d=>setSetup(d.setupRequired)).then(()=>request('/api/auth/me')).then(d=>setAccount(d.account)).catch(e=>{if(e.message!=='Please sign in.')setError(e.message);}).finally(()=>setReady(true));return()=>window.removeEventListener('session-expired',expire);},[]);
 useEffect(()=>{let active=true;if(account)request('/api/workspace/regions').then(d=>{if(!active)return;setRegions(d.regions);setRegion(account.permissions?.allRegions?'ALL':account.region);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[account]);
 async function signIn(event){event.preventDefault();setError('');try{const body=Object.fromEntries(new FormData(event.currentTarget));if(recovering){await post('/api/auth/recover',body);setRecovering(false);setError('Password reset. Sign in with your new password.');return;}const data=await post(`/api/auth/${setup?'setup':'login'}`,body);setAccount(data.account);setView('dashboard');setSetup(false);}catch(e){setError(e.message);}}
 if(!ready)return <div className="auth-shell">Loading workspace…</div>;
 if(!account)return <div className="auth-shell"><form className="auth-card" onSubmit={signIn}><img className="auth-logo" src={sapphireLogo} alt="Sapphire" width="390" height="76"/><div className="eyebrow">DEVPRO · REGIONAL WORKSPACE</div><h1>{setup?'Create analyst administrator':recovering?'Recover account':'Sign in'}</h1><p>{setup?'Set up the Regional Performance Analyst account with access to all three regions.':recovering?'Ask your analyst administrator for a recovery code. Codes expire after 30 minutes.':'Use your assigned account to access your region.'}</p>{setup&&<><FormField label="Your name" name="name"/><FormField label="Administrator setup code" name="code"/><small>Use the private setup code supplied by your server administrator.</small></>}<FormField label="Email" name="email" type="email"/>{recovering&&<FormField label="Recovery code" name="code"/>}<FormField key={setup?'setup':recovering?'recover':'login'} label={setup||recovering?'Password (minimum 4 characters, one capital letter)':'Password'} name="password" type="password" reveal newPassword={setup||recovering}/>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" type="submit">{setup?'Create account':recovering?'Reset password':'Sign in'}</button>{!setup&&<button type="button" className="text-button recovery-link" onClick={()=>{setRecovering(!recovering);setError('');}}>{recovering?'Back to sign in':'Forgot password?'}</button>}</form></div>;
 if(!regions.length)return <div className="auth-shell">{error||'Loading assigned workspace…'}</div>;
 const current=regions.find(r=>r.regionId===region);
 const isOwner=account.email?.toLowerCase()==='liltomsky@gmail.com';
 return <div className="regional-workspace">{account.preview&&<div className="profile-preview-banner"><span>Read-only preview: {account.name} · {roleNames[account.role]} · {account.clusterName||account.zone||account.region}</span><button onClick={async()=>{await post('/api/auth/preview/exit',{});location.reload();}}>Exit preview — return to Babatunde</button></div>}{menuOpen&&<WorkspaceMenu account={account} regions={regions} region={region} view={view} onClose={()=>setMenuOpen(false)} onNavigate={id=>{setView(id);setMenuOpen(false);}} onRegion={id=>{setRegion(id);if(!['executives','reconciliation'].includes(view))setView('dashboard');setMenuOpen(false);}}/>}<header className="region-header"><button className="icon-button workspace-menu-toggle" aria-label="Open sidebar" aria-expanded={menuOpen} aria-controls={menuOpen?'workspace-navigation':undefined} onClick={()=>setMenuOpen(true)}><Menu size={23}/></button><div><strong>DEVPRO</strong><span>{`${roleNames[account.role]} · ${account.permissions?.manageAccess?'Owner':current?.name||'All regions'}`}</span></div><nav aria-label="Regions">{account.permissions?.allRegions&&<button className={region==='ALL'?'selected':''} onClick={()=>{setRegion('ALL');if(!['executives','reconciliation'].includes(view))setView('dashboard');}}>All regions</button>}{regions.map(r=><button key={r.regionId} className={region===r.regionId?'selected':''} onClick={()=>{setRegion(r.regionId);if(!['executives','reconciliation'].includes(view))setView('dashboard');}}>{r.name}</button>)}</nav><button className="text-button" onClick={()=>setView('password')}>Change password</button><button onClick={async()=>{await post('/api/auth/logout',{});setAccount(null);}} className="text-button">Sign out</button></header>
 <div className="workspace-tools"><span>{region==='ALL'?'Cross-region overview':`RBM: ${current?.rbm||'—'}`}</span><button className={view==='dashboard'?'selected':''} onClick={()=>setView('dashboard')}>Dashboard</button>{region!=='ALL'&&<button className={view==='operations'?'selected':''} onClick={()=>setView('operations')}>Team operations</button>}{<button className={view==='executives'?'selected':''} onClick={()=>setView('executives')}>People management</button>}{isOwner&&<button className={view==='reconciliation'?'selected':''} onClick={()=>setView('reconciliation')}>Reconciliation</button>}{account.permissions?.manageAccess&&<button className={view==='accounts'?'selected':''} onClick={()=>setView('accounts')}>Manage access</button>}</div>
 {view==='password'?<ChangePassword onDone={()=>{setAccount(null);setError('Password changed. Please sign in again.');}}/>:view==='accounts'?(account.permissions?.manageAccess?<Deferred><AccessManagement/></Deferred>:<p>Access restricted.</p>):view==='reconciliation'?(isOwner?<Deferred><Reconciliation key={region} region={region}/></Deferred>:<p>Access restricted.</p>):view==='executives'?<Deferred><PeopleManagement key={region} region={region} regions={regions} account={account}/></Deferred>:region==='ALL'&&view==='dashboard'?<Deferred><ManagementOverview regions={regions} request={request} onOpenRegion={id=>{setRegion(id);setView('dashboard');}}/></Deferred>:view==='operations'&&region!=='ALL'?<Deferred><Operations key={region} region={region} account={account} onAnalytics={()=>setView('dashboard')}/></Deferred>:['dashboard','analytics'].includes(view)?<LagosDashboard key={region} account={account} region={region} regionName={current?.name} rbm={current?.rbm} reportingAsOf={current?.reportingAsOf}/>:null}
 </div>;
}
function ChangePassword({onDone}){const [error,setError]=useState('');return <div className="regional-content"><h1>Change password</h1><p>Changing your password signs out all existing sessions.</p><form className="workspace-form" onSubmit={async e=>{e.preventDefault();try{await post('/api/auth/change-password',Object.fromEntries(new FormData(e.currentTarget)));onDone();}catch(e){setError(e.message);}}}><FormField label="Current password" name="currentPassword" type="password"/><FormField label="New password" name="password" type="password" newPassword/><button className="button primary">Change password</button></form>{error&&<p role="alert" className="form-error">{error}</p>}</div>;}
