import test from 'node:test';
import assert from 'node:assert/strict';
import {buildDashboard} from '../server/services/dashboard.js';
const period={month:'2026-09',asOf:'2026-09-03',workingDates:['2026-09-01','2026-09-02','2026-09-03','2026-09-04'],availableDates:['2026-09-01','2026-09-03'],zoneTargets:[{zone:'East',valueKobo:100000},{zone:'West',valueKobo:200000}],approvedCount:2,approvedValueKobo:30000};
const records=[{businessDate:'2026-09-01',sourceZone:'East',valueKobo:10000,agent:'a',cluster:'c',transactionId:'1',sourceAgentName:'Agent',identityMethod:'POLICY_ID'},{businessDate:'2026-09-03',sourceZone:'West',valueKobo:20000,transactionId:'2',sourceAgentName:'Unmapped',identityMethod:'FINGERPRINT'}];
const args={period,records,roster:[{_id:'a',agentId:'A1',fullName:'Agent',currentCluster:'c'}],clusters:[{_id:'c',name:'East 1',zone:'East'}]};
test('dashboard money, pace and breakdowns reconcile without excluding unattributed sales',()=>{const d=buildDashboard(args);assert.equal(d.summary.value,300);assert.equal(d.summary.count,2);assert.equal(d.summary.expected,2250);assert.equal(d.summary.gap,-1950);assert.equal(d.summary.forecast,400);for(const key of ['zones','agents','clusters'])assert.equal(d[key].reduce((a,r)=>a+r.value,0),300);assert.equal(d.quality.outsideRoster,1);assert.equal(d.quality.fingerprints,1);});
test('zone/date filters share a consistent reporting scope and missing days remain null',()=>{const d=buildDashboard({...args,zone:'East',asOf:'2026-09-02'});assert.equal(d.summary.value,100);assert.equal(d.summary.target,1000);assert.equal(d.transactions.length,1);assert.equal(d.timeline[1].value,null);assert.equal(d.timeline[1].count,null);assert.throws(()=>buildDashboard({...args,zone:'Unknown'}));});
test('custom ranges are inclusive, restart cumulative totals and prorate targets to selected selling days',()=>{const d=buildDashboard({...args,from:'2026-09-03',asOf:'2026-09-03'});assert.equal(d.summary.value,200);assert.equal(d.summary.count,1);assert.equal(d.summary.expected,750);assert.equal(d.summary.forecast,800);assert.equal(d.zones.reduce((sum,row)=>sum+row.forecast,0),800);assert.equal(d.agents.reduce((sum,row)=>sum+row.forecast,0),800);assert.equal(d.summary.requiredRate,null);assert.equal(d.timeline.length,1);assert.equal(d.timeline[0].cumulative,200);assert.equal(d.transactions[0].id,'2');assert.throws(()=>buildDashboard({...args,from:'2026-09-04',asOf:'2026-09-03'}));});
test('agent targets retain departed allocations and missing targets without losing or duplicating sales',()=>{const d=buildDashboard({...args,period:{...period,agentTargets:[{agentId:'A1',name:'Agent',zone:'East',valueKobo:100000,employmentStatus:'ACTIVE'},{name:'Unmapped',zone:'West',valueKobo:200000,employmentStatus:'RESIGNED',pendingAction:'Transfer later'},{name:'Departed',zone:'West',valueKobo:300000,employmentStatus:'EXITED'}]}});const agent=d.agents.find(a=>a.id==='A1');assert.equal(agent.target,1000);assert.equal(agent.achievement,.1);assert.equal(agent.expected,750);assert.equal(agent.gap,-650);assert.equal(agent.forecast,100/3*4);assert.equal(d.agents.find(a=>a.name==='Unmapped').value,200);assert.equal(d.agents.find(a=>a.name==='Departed').value,0);assert.equal(d.targetAllocation.pending,5000);assert.equal(d.agents.reduce((a,r)=>a+r.value,0),300);const missing=buildDashboard(args).agents[0];assert.equal(missing.target,null);assert.equal(missing.achievement,null);assert.equal(missing.expected,null);assert.equal(missing.gap,null);});
test('missing regional targets remain null, while forecasts use the reporting calendar',()=>{const p={...period,region:'NOR',zoneTargets:[{zone:'East',valueKobo:null},{zone:'West',valueKobo:null}]};const d=buildDashboard({...args,period:p});assert.equal(d.summary.target,null);assert.equal(d.summary.expected,null);assert.equal(d.summary.gap,null);assert.equal(d.summary.pace,null);assert.equal(d.summary.requiredRate,null);assert.equal(d.summary.forecast,400);assert.equal(d.timeline[0].expected,null);assert.equal(d.timeline[0].requiredDaily,null);assert(d.zones.every(r=>r.target===null&&r.gap===null));});
test('known regional target does not assign an omitted state a zero target',()=>{const d=buildDashboard({...args,period:{...period,region:'SSE',regionalMonthlyTargetKobo:100000,zoneTargets:[{zone:'East',valueKobo:100000},{zone:'West',valueKobo:null}]}});assert.equal(d.summary.target,1000);assert.equal(d.summary.expected,750);const west=d.zones.find(r=>r.name==='West');assert.equal(west.target,null);assert.equal(west.gap,null);assert.equal(west.value,200);const filtered=buildDashboard({...args,zone:'West',period:{...period,regionalMonthlyTargetKobo:100000,zoneTargets:[{zone:'West',valueKobo:null}]}});assert.equal(filtered.summary.target,null);});

test("forecast is unavailable when a selection has no selling days",()=>{const d=buildDashboard({...args,from:"2026-09-03",asOf:"2026-09-03",period:{...period,workingDates:["2026-09-01","2026-09-02"]}});assert.equal(d.summary.forecast,null);assert(d.zones.every(row=>row.forecast===null));});
