import {Router} from 'express';import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';import {readFile,writeFile,mkdir} from 'node:fs/promises';import bcrypt from 'bcryptjs';import {rateLimit} from 'express-rate-limit';import {Account,LoginSession,regionIds} from '../models/index.js';import {requireAnalyst,isOwner} from '../middleware/access.js';
import {accessProfilesRouter,publicProfile} from './access-profiles.js';
import {lifecycleRouter,initializeLifecycle,validPassword} from './account-lifecycle.js';
export const authRouter=Router();const digest=s=>createHash('sha256').update(s).digest('hex');const publicAccount=publicProfile;
export async function initializeAuth(){await initializeLifecycle();await Account.createIndexes();await LoginSession.createIndexes();if(!await Account.exists({})){if(process.env.NODE_ENV==='production'){if(!process.env.ADMIN_SETUP_CODE||process.env.ADMIN_SETUP_CODE.length<32)throw Error('Set ADMIN_SETUP_CODE (at least 32 characters) for initial production setup');return;}await mkdir('.local',{recursive:true});try{await readFile('.local/analyst-setup-code');}catch{await writeFile('.local/analyst-setup-code',randomBytes(24).toString('hex'),{mode:0o600,flag:'wx'});}}}
export function sameOrigin(request,response,next){if(['GET','HEAD','OPTIONS'].includes(request.method))return next();const origin=request.get('origin');const allowed=new Set([process.env.CLIENT_ORIGIN||'http://127.0.0.1:5173',...(process.env.NODE_ENV==='production'?[]:['http://127.0.0.1:3001'])]);if(origin&&!allowed.has(origin)||request.get('x-dashboard-request')!=='1')return response.status(403).json({error:'Invalid request origin.'});next();}
export async function authenticate(request,response,next){try{const cookie=request.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('sales_session='))?.slice(14);if(!cookie)return response.status(401).json({error:'Please sign in.'});const session=await LoginSession.findOne({tokenHash:digest(cookie),expiresAt:{$gt:new Date()}}).lean();const account=session&&await Account.findOne({_id:session.account,active:true}).lean();if(!account)return response.status(401).json({error:'Session expired. Please sign in.'});request.realAccount=account;request.account=account;request.sessionHash=session.tokenHash;request.preview=false;if((session.previewAccount||session.previewProfile)&&isOwner(account)){const target=session.previewProfile||await Account.findById(session.previewAccount).lean();if(target){request.account=target;request.preview=true;}}if(request.preview&&!['GET','HEAD','OPTIONS'].includes(request.method)&&!request.originalUrl.endsWith('/preview/exit')&&!request.originalUrl.endsWith('/logout'))return response.status(403).json({error:'Profile preview is read-only. Exit preview to make changes.'});next();}catch(e){next(e);}}
async function login(response,account){const token=randomBytes(32).toString('hex');await LoginSession.create({tokenHash:digest(token),account:account._id,expiresAt:new Date(Date.now()+12*3600000)});response.cookie('sales_session',token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='true',maxAge:12*3600000,path:'/'});response.json({account:publicAccount(account)});}
const credentials=body=>typeof body.name==='string'&&body.name.trim().length>=2&&typeof body.email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email)&&validPassword(body.password);
authRouter.use(sameOrigin);authRouter.use(rateLimit({windowMs:15*60*1000,limit:50}));
authRouter.get('/status',async(req,res)=>res.json({setupRequired:!await Account.exists({})}));
authRouter.post('/setup',async(req,res,next)=>{try{if(await Account.exists({}))return res.status(409).json({error:'Administrator setup is already complete.'});if(!credentials(req.body))return res.status(400).json({error:'Supply name, valid email and a password of at least 4 characters including one capital letter (maximum 72 UTF-8 bytes).'});const expected=process.env.ADMIN_SETUP_CODE||(await readFile('.local/analyst-setup-code','utf8')).trim();if(typeof req.body.code!=='string'||!timingSafeEqual(Buffer.from(digest(req.body.code.trim())),Buffer.from(digest(expected))))return res.status(403).json({error:'Incorrect setup code.'});const account=await Account.create({_id:'000000000000000000000001',name:req.body.name,email:req.body.email.trim().toLowerCase(),passwordHash:await bcrypt.hash(req.body.password,12),role:'ANALYST',region:'ALL'});await login(res,account);}catch(e){if(e.code===11000)return res.status(409).json({error:'Setup already completed.'});next(e);}});
authRouter.post('/login',async(req,res,next)=>{try{if(typeof req.body.email!=='string'||typeof req.body.password!=='string'||req.body.password.length>72)return res.status(400).json({error:'Invalid credentials.'});const a=await Account.findOne({email:req.body.email.trim().toLowerCase(),active:true}).select('+passwordHash');if(!a||!await bcrypt.compare(req.body.password,a.passwordHash))return res.status(401).json({error:'Email or password is incorrect.'});await login(res,a);}catch(e){next(e);}});
authRouter.get('/me',authenticate,(req,res)=>res.json({account:{...publicAccount(req.account),preview:req.preview,permissions:{...publicAccount(req.account).permissions,...(req.preview?{manageAccess:false,peopleRegions:[]}: {})}}}));
authRouter.post('/logout',authenticate,async(req,res)=>{await LoginSession.deleteOne({tokenHash:req.sessionHash});res.clearCookie('sales_session',{path:'/'}).json({ok:true});});
authRouter.use(accessProfilesRouter(authenticate));
authRouter.use(lifecycleRouter(authenticate));
